# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Думан\PycharmProjects\Lab9_GUI_chat\LoginPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(388, 433)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(30, 70, 71, 31))
        self.label.setObjectName("label")
        self.usernameField = QtWidgets.QTextEdit(Form)
        self.usernameField.setGeometry(QtCore.QRect(120, 70, 131, 31))
        self.usernameField.setObjectName("usernameField")
        self.authenticateButton = QtWidgets.QPushButton(Form)
        self.authenticateButton.setGeometry(QtCore.QRect(120, 140, 101, 41))
        self.authenticateButton.setObjectName("authenticateButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Username:"))
        self.authenticateButton.setText(_translate("Form", "Authenticate"))
