# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PrivateChat.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(401, 658)
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(20, 110, 271, 461))
        self.textBrowser.setObjectName("textBrowser")
        self.publicModeButton = QtWidgets.QPushButton(Form)
        self.publicModeButton.setGeometry(QtCore.QRect(320, 570, 81, 41))
        self.publicModeButton.setObjectName("publicModeButton")
        self.textField = QtWidgets.QTextEdit(Form)
        self.textField.setGeometry(QtCore.QRect(0, 620, 131, 41))
        self.textField.setObjectName("textField")
        self.sendButton = QtWidgets.QPushButton(Form)
        self.sendButton.setGeometry(QtCore.QRect(320, 620, 81, 41))
        self.sendButton.setObjectName("sendButton")
        self.logsButton = QtWidgets.QPushButton(Form)
        self.logsButton.setGeometry(QtCore.QRect(320, 520, 81, 31))
        self.logsButton.setObjectName("logsButton")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 20, 351, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 580, 71, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(160, 590, 111, 21))
        self.label_3.setObjectName("label_3")
        self.destinationUsername = QtWidgets.QTextEdit(Form)
        self.destinationUsername.setGeometry(QtCore.QRect(150, 620, 151, 41))
        self.destinationUsername.setObjectName("destinationUsername")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(10, 60, 331, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.publicModeButton.setText(_translate("Form", "Public Mode"))
        self.textField.setHtml(_translate("Form",
                                          "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                          "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                          "p, li { white-space: pre-wrap; }\n"
                                          "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
                                          "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.sendButton.setText(_translate("Form", "Send"))
        self.logsButton.setText(_translate("Form", "Logs"))
        self.label.setText(_translate("Form", "            Telegram Private Mode"))
        self.label_2.setText(_translate("Form", "Message:"))
        self.label_3.setText(_translate("Form", "Username of receiver:"))
        self.label_4.setText(_translate("Form", "Private mode is not working yet, problems with signal"))
